apiVersion: v1
kind: PersistentVolume
metadata:
  name: trilium-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: '/mnt/trilium-data'
  persistentVolumeReclaimPolicy: Retain
